<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\config.props" />

  <PropertyGroup>
    <PackageId>TnmsPluginFoundation</PackageId>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.123" ExcludeAssets="runtime" />
    <PackageReference Include="ModSharp.Sharp.Modules.TargetingManager.Shared" Version="2.1.123" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Wuling\Wuling.Abstract\Wuling.Abstract.csproj" Private="false" ExcludeAssets="runtime" />
  </ItemGroup>
  
</Project>
