<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\config.props" />

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.123" ExcludeAssets="runtime" />
        <ProjectReference Include="..\TnmsPluginFoundation\TnmsPluginFoundation.csproj" Private="false" ExcludeAssets="runtime" PrivateAssets="runtime"/>
    </ItemGroup>
</Project>
